### ISSUE TITLE
Horizontal diagnostics alignment

### ISSUE THREAD

**Issue by SWiegandt** [MeanderingProgrammer/py-requirements.nvim#4]
Very subjective and purely aesthetic proposal, but being back at work with a considerably larger requirements.txt than I had previously tested with, the alignment of the diagnostics made it difficult for me to quickly parse the file.

I added a dirty hack to my config as a POC to align the diagnostics horizontally based on the longest line in the file, which as of now works in Neovim nightly (`virt_text_win_col` isn't configurable in latest), but could potentially be manually padded in latest if desired.

I don't know if this should just be left up to each user to configure themselves if they want it, or if we could add some configuration to enable it (maybe with a caveat that nightly is needed for now). I'll attach my hack and some illustrations:

```lua
local display = require("py-requirements.ui").display
require("py-requirements.ui").display = function(buf, modules)
	display(buf, modules)
	local max_width = 0

	for _, module in ipairs(modules) do
		local lines = vim.api.nvim_buf_get_lines(buf, module.line_number, module.line_number + 1, false)

		if #lines == 0 then
			return
		end

		if #lines[1] > max_width then
			max_width = #lines[1]
		end
	end

	vim.diagnostic.config(
		{ virtual_text = { virt_text_win_col = max_width } },
		vim.api.nvim_create_namespace("py-requirements.nvim")
	)
end
```
<img width="487" alt="Screenshot 2024-01-29 at 11 50 28" src="https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/12746569/a675d0e7-0bf0-4430-b7e3-2dd5d36008b4">
<img width="577" alt="Screenshot 2024-01-29 at 11 49 51" src="https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/12746569/de37bfcf-f962-4eb2-9777-dd6386cd3530">

**Comment by MeanderingProgrammer** [comment]
Thanks for bringing that up, I agree, not the prettiest thing.

I pushed a fix very similar to the one you put together here: https://github.com/MeanderingProgrammer/py-requirements.nvim/commit/8c4ed8ec5861b826ff7a1c9e588c1231139fd108.

Main difference was rather than using the nightly feature of the diagnostic (which is nice), I used extmarks to show the message rather than the diagnostic itself. There we can provide the same `virt_text_win_col` parameter as part of the latest release. It's kind of clunky and I'll come around to it at some point in the future to remove the duplicate information (if I remember haha).

Let me know how it works for you!

**Comment by SWiegandt** [comment]
I considered setting manual extmarks as well, given that that's where the nightly parameter was copied from, but concluded that it was a lot more work and didn't really like how it's essentially bypassing built-in functionality to display the diagnostics. There's also the issue that you can no longer set `virtual_text = false` in your diagnostic config if you only want them to show up in Trouble, for instance, but I guess there could be a configuration setting in the plugin to disable showing the extmarks if that is desired.

For me personally it works great and as intended though. 👍
