### ISSUE TITLE
Regression from autocmd pattern when using pip-tools

### ISSUE THREAD

**Issue by SWiegandt** [MeanderingProgrammer/py-requirements.nvim#8]
The addition of the `*.txt` pattern in [8f195bb](https://github.com/MeanderingProgrammer/py-requirements.nvim/commit/8f195bb728aa6666f7ec9386b1d5cc5ed637bbc5) causes a potential regression when using pip-tools, since it's common to name your requirements source file `requirements.in` in that case. I don't see an easy way to parse a vim pattern from a general regex, since just splitting on periods isn't reliable, but I'm also not sure if the autocmd pattern is all that necessary without the `TextChangedI` event, given that the remaining events are triggered fairly seldomly?

**Comment by MeanderingProgrammer** [comment]
Ah, had not considered that, damn.
I was trying to avoid having the auto command callback called all the time in the background.
If I remove the pattern the callback gets triggered even when editing `main.py` or whatever each time text gets modified in the buffer.
The work done isn't much, it'll try to match the regexes to the file name and then do nothing.
I'll remove it since I don't think this would be anything noticeable.

Thanks for reporting the issue!

**Comment by MeanderingProgrammer** [comment]
Merged: https://github.com/MeanderingProgrammer/py-requirements.nvim/commit/a23ff6ec5837fade0656bad8f830dc9cda52d8c3
